### ISSUE TITLE
Honor :id assigned with `assign_new`

### ISSUE THREAD

**Issue by patcoll** [Serabe/live_isolated_component#21]
On 0.6.2 on LV 0.18.11.

We are using `assign_new` to help generate some unique IDs for components that need unique IDs. We are generating UUIDs for these components, and using `assign_new` to do that.

For some reason during a test, the function passed into `assign_new`, that should be lazily run, is not being run as expected.

**Comment by Serabe** [comment]
Is the new test in #26 what you wanted? 

![2023-03-05 at 14 36](https://user-images.githubusercontent.com/36221/222963845-4c059b54-0417-410f-95ec-603ae15d5867.png)
