### ISSUE TITLE
Phoenix 1.7 support

### ISSUE THREAD

**Issue by TheFirstAvenger** [Serabe/live_isolated_component#22]
Just adding an issue to track support for Phoenix 1.7 now that it is out. `live_isolated_component` is currently tied to 1.6

**Comment by Serabe** [comment]
@TheFirstAvenger Just published [live_isolated_component 0.5.2](https://hex.pm/packages/live_isolated_component/0.5.2) for supporting Phoenix 1.7 with LiveView 0.17. I'll be working on the main branch for support with LV 0.18

**Comment by Serabe** [comment]
@TheFirstAvenger Just published [live_isolated_component 0.6.3](https://hex.pm/packages/live_isolated_component/0.6.3) as well.

**Comment by Serabe** [comment]
@piacsek vesion 0.8.0 does!
