### ISSUE TITLE
Postgres disconnected errors

### ISSUE THREAD

**Issue by RobertoSchneiders** [Serabe/live_isolated_component#37]
I'm testing your library and I'm having one small issue. When the live component does any database operations, like, creating or updating a record, I get this error in the logs:
```
[error] Postgrex.Protocol (#PID<0.596.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.672.0> exited
```

The tests run just fine despite the error message in the logs. I'm wondering if it has anything to do with the agents or async tasks in general.

**Comment by Serabe** [comment]
Do you have a reproduction I can take a look at? I’m happy to take a look at it!

Thank you!

Sergio Arbeo

**Comment by RobertoSchneiders** [comment]
I'll be out for 2 weeks but I will try to modify the test web app to replicate this issue when I'm back. I let you know. 

Thank you.

**Comment by Serabe** [comment]
Any updates?

**Comment by RobertoSchneiders** [comment]
@Serabe sorry I didn't get back to you sooner. I couldn't replicate this issue outside of my project and I no longer believe this is an issue with the live_isolated_component library. It's somewhat random and difficult to debug but I repeated some tests today without the live_isolated_component library in the project and got the same issues so it must be something else. thank you
